# Generated by Django 4.2.1 on 2023-05-23 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventos", "0004_certificado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="participantes",
            field=models.ManyToManyField(
                blank=True,
                related_name="evento_participante",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
